apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: serverest
  annotations:
    github.com/project-slug: bellatriz/ServeRest
    sonarqube.org/project-key: bellatriz_ServeRest
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: >
    openapi: 3.0.1
    servers:
      - url: https://serverest.dev/
