apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: serverest
  annotations:
    github.com/project-slug: bellatriz/ServeRest
    sonarqube.org/project-key: bellatriz_ServeRest
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    swagger: "2.0.0"
    info:
      version: 1.0.0
      title: Swagger Serverest
    servers:
      - url: https://serverest.dev/
