name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ServeRest/ServeRest/.github/workflows/reusable_workflow.yml@exemplo-reutilizar-workflow
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-mutation-diff:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: docker-compose build test-mutation-diff
    - name: Run mutation test - Changed files in the branch
      run: make test-mutation-diff
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  test-contract:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - run: docker-compose build test-contract
    - name: Run contract test
      run: make test-contract
      env:
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
